### ISSUE TITLE
Perhaps some projects by divestedcg and rusty-snake should be considered for addition

### ISSUE THREAD

**Issue by throwaway43** [34N0/awesome-fedora-security#2]
### Link to suggestion

https://github.com/divestedcg/rpm-hardened_malloc

### Describe your suggesiton

First of all, I am deeply grateful for the time and effort you've put into curating this excellent collection! Through it, I've discovered several fascinating initiatives that have piqued my curiosity. I'm also excited to explore other projects that you may add in the future.

Secondly, I'm unaware of any guidelines for submitting suggestions. So apologies if what I'll suggest doesn't fit the bill.

A couple of interesting projects like [Brace](https://github.com/divestedcg/Brace), [rpm-hardened_malloc](https://github.com/divestedcg/rpm-hardened_malloc) and [real-ucode](https://github.com/divestedcg/real-ucode) by [divestedcg](https://github.com/divestedcg) (perhaps better known as [Divested Computing Group](https://divested.dev/index.html#splash); the ones responsible for the excellent [DivestOS Mobile](https://divestos.org/)) are IMO worthy of being considered. The already listed rpm-hardened_malloc by solidc0re is a fork of theirs even. Though, in contrast to the one maintained by solidc0re, divestedcg's maintained package has received updates recently. Therefore, it seems to be necessarily superior.

Small shout-out to [rusty-snake](https://github.com/rusty-snake) as their security projects are perhaps also worth considering.

**Comment by 34N0** [comment]
But thank you for the suggestion. In the current state secureblue allready implements hardened_malloc. And thank you for mentioning the rest of the mentioned projects.

**Comment by wandapeter** [comment]
Hey!

Thank you for the suggestions, i will look at them. But feel free to create a PR with your favourite, missing projects added! :smile:
